import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopMiniBar from "@/components/topminibar";
import Header from "@/components/header";
import BlueNav from "@/components/bluenav";
import MobileBottomNav from "@/components/mobilebottomnav";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import { TooltipProvider } from "@/components/ui/tooltip";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopMiniBar />
        <Header />
        {/* <BlueNav /> */}
        <TooltipProvider>{children}</TooltipProvider>
        {/* <Footer />
        <MobileBottomNav /> */}
      </body>
    </html>
  );
}
