"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "tw" | "fr" | "ewe" | "ga";

export const translations = {
  en: {
    // Navigation & Topbar
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.about": "About Us",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.dashboard": "Dashboard",
    "nav.admin_dashboard": "Admin Dashboard",
    "topbar.shopping_center": "Shopping center for all orders over GH₵100",
    "topbar.store_location": "Store Location",
    "topbar.track_order": "Track Your Order",

    // Header & Search
    "search.all_categories": "All Categories",
    "search.placeholder": "I'm shopping for...",
    "search.mobile_placeholder": "Search something...",
    "search.button": "Search",
    "auth.login": "Login",
    "auth.register": "Register",
    "nav.navigation": "Navigation",

    // Hero Banner
    "hero.exclusive_deals": "Exclusive Deals",
    "hero.up_to_50_off": "Up to 50% Off",
    "hero.shop_now": "Shop Now",
    "hero.view_all_deals": "View all deals",
    "hero.new_arrival": "New Arrival",
    "hero.discover_now": "Discover Now →",
    "hero.limited_time": "Limited Time",
    "hero.save_big": "Save Big Today →",

    // Cart & Wishlist
    "cart.title": "Cart",
    "cart.your_cart": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.empty_desc": "Add items to your cart to see them here.",
    "cart.checkout": "Checkout",
    "cart.subtotal": "Subtotal",
    "cart.total": "Total",
    "cart.add": "Add to cart",
    "cart.in_cart": "In Cart",
    "cart.continue_shopping": "Continue shopping",
    "wishlist.title": "Wishlist",
    "wishlist.your_wishlist": "Your Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.empty_desc": "Save items you love for later.",
    "wishlist.view": "View",

    // Features
    "feature.free_delivery.title": "Free Delivery",
    "feature.free_delivery.desc": "For all orders over GH₵50",
    "feature.return.title": "90 Days Return",
    "feature.return.desc": "If goods have problems",
    "feature.payment.title": "Secure Payment",
    "feature.payment.desc": "100% secure payment",
    "feature.support.title": "24/7 Support",
    "feature.support.desc": "Dedicated support",

    // Sections & Products
    "section.category_month": "Top categories of the month",
    "section.deal_of_day": "Deal of the day",
    "section.recommended_for_you": "Recommended for you",
    "section.end_in": "End in:",
    "section.view_all": "View All",
    "section.groceries": "Fresh Groceries & Daily Essentials",
    "section.electronics": "Digital Electronics & Accessories",
    "banner.summer_fashion": "Summer Fashion",
    "banner.summer_discount": "Up to 40% off selected styles",
    "status.fetching_styles": "Fetching the latest styles...",
    "status.failed_load": "Failed to load products.",
    "status.no_products": "No products found.",
    "product.each": "each",
    "product.out_of_stock": "Out of stock",
    "product.in_cart_badge": "In cart ✓",
    "product.add_to_cart": "Add to cart",
    "product.buy_now": "Buy Now",
    "product.wishlisted": "Wishlisted",
    "product.add_to_wishlist": "Add to wishlist",
    "product.sale": "Sale",

    // Footer
    "footer.quick_links": "Quick links",
    "footer.company": "Company",
    "footer.business": "Business",
    "footer.newsletter": "Newsletter",
    "footer.subscribe": "Subscribe",
    "footer.email_placeholder": "Email Address",
    "footer.newsletter_desc": "Subscribe to get special offers and updates",
    "footer.rights": "©2026 Martfury. All Rights Reserved.",
    "footer.safe_payment": "We Using Safe Payment For",
    "footer.policy": "Policy",
    "footer.terms": "Terms & Conditions",
    "footer.shipping": "Shipping",
    "footer.returns": "Returns",
    "footer.faqs": "FAQs",
    "footer.about": "About Us",
    "footer.affiliate": "Affiliate",
    "footer.careers": "Careers",
    "footer.contact": "Contact",
    "footer.our_press": "Our Press",
    "footer.checkout": "Checkout",
    "footer.my_account": "My account",
    "footer.shop": "Shop",

    // Account & Mobile
    "account.title": "Account",
    "language.title": "Language",
    "language.en": "English",
    "language.tw": "Twi",

    // Checkout
    "checkout.contact_information": "Contact information",
    "checkout.already_have_account": "Already have an account?",
    "checkout.log_in": "Log in",
    "checkout.email_placeholder": "Email",
    "checkout.email_offers": "Email me with news and offers",
    "checkout.shipping_address": "Shipping address",
    "checkout.first_name": "First name",
    "checkout.last_name": "Last name",
    "checkout.company_optional": "Company (optional)",
    "checkout.address_placeholder": "Address",
    "checkout.suburb_placeholder": "Suburb",
    "checkout.country_region": "Country/region",
    "checkout.state_territory": "State/territory",
    "checkout.postcode_placeholder": "Postcode",
    "checkout.phone_placeholder": "Phone",
    "checkout.return_to_shop": "‹ Return to shop",
    "checkout.refund_policy": "Refund policy",
    "checkout.privacy_policy": "Privacy policy",
    "checkout.gift_card_placeholder": "Gift card or discount code",
    "checkout.apply": "Apply",
    "checkout.remove": "Remove",
    "checkout.discount": "Discount",
    "checkout.shipping_label": "Shipping",
    "checkout.free": "Free",
    "checkout.total_label": "Total",
    "checkout.including": "Including",
    "checkout.in_taxes": "in taxes",
    "checkout.checkout_with": "Checkout with",
    "checkout.connecting": "Connecting...",
    "checkout.processing_with": "Processing payment with",
    "checkout.please_wait": "Please wait",
    "checkout.connecting_securely": "Connecting securely to payment provider. Do not close or refresh this page.",

    // Shop / filters
    "shop.search_placeholder": "Search products...",
    "shop.filters": "Filters",
    "shop.categories": "Categories",
    "shop.price_range": "Price Range",
    "shop.rating": "Rating",
    "shop.clear_filters": "Clear Filters",
    "shop.sort_by": "Sort by",
    "shop.showing_results": "Showing results",
    "shop.grid_view": "Grid view",
    "shop.list_view": "List view",
    "shop.apply_filters": "Apply Filters",
    "shop.search_heading": "Search",
    "shop.by_rating": "By Rating",
    "shop.by_price": "By Price",
    "shop.reset": "Reset",
    "shop.price_prefix": "Price:",
    "shop.and_up": "& Up",
    "shop.stars": "Stars",

    // Product tabs
    "tabs.description": "Description",
    "tabs.specification": "Specification",
    "tabs.vendor": "Vendor",
    "tabs.reviews": "Reviews",
    "tabs.qa": "Questions & Answers",
    "tabs.no_description": "No description available for this product.",
  },
  tw: {
    // Navigation & Topbar
    "nav.home": "Ahyaseɛ",
    "nav.shop": "Guadwam",
    "nav.about": "Yɛn Ho Asɛm",
    "nav.blog": "Nsɛm Kwa",
    "nav.contact": "Nkitahodi",
    "nav.dashboard": "Panin Krasiam",
    "nav.admin_dashboard": "Panin Krasiam",
    "topbar.shopping_center": "Guadwam kɛseɛ ma mpotamu nneɛma a ɛboro GH₵100 nyinaa",
    "topbar.store_location": "Beaeɛ a Yɛwɔ",
    "topbar.track_order": "Di Wo Nneɛma Akyi",

    // Header & Search
    "search.all_categories": "Nneɛma Mmoa Nyinaa",
    "search.placeholder": "Rɛhwehwɛ nneɛma bi a wobɛtɔ...",
    "search.mobile_placeholder": "Hwehwɛ adeɛ bi...",
    "search.button": "Hwehwɛ",
    "auth.login": "Wura Mu",
    "auth.register": "Kyerɛ Wo Dzin Mu",
    "nav.navigation": "Akwanmuka",

    // Hero Banner
    "hero.exclusive_deals": "Nneɛma a Ɛsom Boɔ soronko",
    "hero.up_to_50_off": "So ate kɔsi 50%",
    "hero.shop_now": "Tɔ Seesei",
    "hero.view_all_deals": "Hwɛ nneɛma a agye boɔ nyinaa",
    "hero.new_arrival": "Deɛ Ɛbaaeɛ Foforɔ",
    "hero.discover_now": "Hwehwɛ Mu Seesei →",
    "hero.limited_time": "Bere Tiawa",
    "hero.save_big": "Gye Sika Kɛseɛ Nnɛ →",

    // Cart & Wishlist
    "cart.title": "Kɛntɛn",
    "cart.your_cart": "Wo Kɛntɛn",
    "cart.empty": "Gye sɛ nneɛma biara nni wo kɛntɛn mu",
    "cart.empty_desc": "De nneɛma gu wo kɛntɛn mu na hwɛ wɔ ha.",
    "cart.checkout": "Tua Ka",
    "cart.subtotal": "Sika Aka Nyinaa",
    "cart.total": "Ka a Wɔtua Nyinaa",
    "cart.add": "De Gu Kɛntɛn Mu",
    "cart.in_cart": "Egu Kɛntɛn Mu Dadaw",
    "cart.continue_shopping": "Kɔ So Tɔ Nneɛma",
    "wishlist.title": "Deɛ Me Pɛ",
    "wishlist.your_wishlist": "Deɛ Me Pɛ Nyinaa",
    "wishlist.empty": "Gye sɛ nneɛma biara nni deɛ wo pɛ mu",
    "wishlist.empty_desc": "Kora nneɛma a wo pɛ ma daakye.",
    "wishlist.view": "Hwɛ",

    // Features
    "feature.free_delivery.title": "De Kɔ Ma Wo Kwa",
    "feature.free_delivery.desc": "Wɔ nneɛma a ɛboro GH₵50 nyinaa so",
    "feature.return.title": "Nda 90 San De Brɛ Yɛn",
    "feature.return.desc": "Sɛ nneɛma no nni kwan so a",
    "feature.payment.title": "Banbɔ Akatua",
    "feature.payment.desc": "100% banbɔ akatua pa",
    "feature.support.title": "Nkitahodi Bere Nyinaa (24/7)",
    "feature.support.desc": "Nkitahodi a ɛyɛ fɛ",

    // Sections & Products
    "section.category_month": "Nneɛma Mmoa a Ɛsom Boɔ Wɔ Bosome Mu",
    "section.deal_of_day": "Adeɛ a Ɛsom Boɔ Nnɛ",
    "section.recommended_for_you": "Deɛ Yɛfa Kyerɛ Wo",
    "section.end_in": "Ɛtwam wɔ:",
    "section.view_all": "Hwɛ Ne Nyinaa",
    "section.groceries": "Aduan Foforɔ & Da Biara Nneɛma",
    "section.electronics": "Elektrɔniks & Nneɛma Nketewa",
    "banner.summer_fashion": "Ahuhuro Bere Ntadeɛ",
    "banner.summer_discount": "So ate kɔsi 40% wɔ ntadeɛ bi so",
    "status.fetching_styles": "Rɛwefɛ ntadeɛ foforɔ no...",
    "status.failed_load": "Nneɛma no amba yie.",
    "status.no_products": "Amanya nneɛma biara.",
    "product.each": "biara",
    "product.out_of_stock": "Nsene nni hɔ",
    "product.in_cart_badge": "Egu kɛntɛn mu ✓",
    "product.add_to_cart": "De gu kɛntɛn mu",
    "product.buy_now": "Tɔ Seesei",
    "product.wishlisted": "Ekora Mu Dadaw",
    "product.add_to_wishlist": "De ka deɛ me pɛ ho",
    "product.sale": "So Ate",

    // Footer
    "footer.quick_links": "Nkitahodi Ntɛm",
    "footer.company": "Kɔmpani",
    "footer.business": "Dwa / Adwuma",
    "footer.newsletter": "Krasiam Nsɛm",
    "footer.subscribe": "Mene Ho Dzin",
    "footer.email_placeholder": "Wo Email Beaeɛ",
    "footer.newsletter_desc": "Mene wo dzin na nya nneɛma a agye boɔ ne afoforɔ",
    "footer.rights": "©2026 Martfury. Wɔabɔ ne nyinaa ho ban.",
    "footer.safe_payment": "Yɛde Banbɔ Tua Ka Di Dwuma Ma",
    "footer.policy": "Mmara & Nhyehyɛeɛ",
    "footer.terms": "Mmara ne Ahyɛdeɛ",
    "footer.shipping": "De Kɔ Ma Wo",
    "footer.returns": "De San Brɛ Yɛn",
    "footer.faqs": "Nsemmisa ne Mmuaeɛ",
    "footer.about": "Yɛn Ho Asɛm",
    "footer.affiliate": "Nkitahodi Dwuma",
    "footer.careers": "Adwuma Beaeɛ",
    "footer.contact": "Nkitahodi",
    "footer.our_press": "Yɛn Dawurbɔ",
    "footer.checkout": "Tua Ka",
    "footer.my_account": "Me Akawnt",
    "footer.shop": "Guadwam",

    // Account & Mobile
    "account.title": "Me Akawnt",
    "language.title": "Kasa",
    "language.en": "English",
    "language.tw": "Twi",

    // Checkout
    "checkout.contact_information": "Wo Ho Nsɛm",
    "checkout.already_have_account": "Wowɔ akawnt dada anaa?",
    "checkout.log_in": "Wura Mu",
    "checkout.email_placeholder": "Email",
    "checkout.email_offers": "Fa nsɛm ne ho nneɛma brɛ me wɔ email so",
    "checkout.shipping_address": "Beaeɛ a Wɔde Nneɛma Bɛkɔ",
    "checkout.first_name": "Din a Edi Kan",
    "checkout.last_name": "Abusua Din",
    "checkout.company_optional": "Adwumakuo (Ɛho Nhia)",
    "checkout.address_placeholder": "Beaeɛ",
    "checkout.suburb_placeholder": "Kurotia",
    "checkout.country_region": "Ɔman/Mantam",
    "checkout.state_territory": "Ɔmantam",
    "checkout.postcode_placeholder": "Post Nɔma",
    "checkout.phone_placeholder": "Telefon Nɔma",
    "checkout.return_to_shop": "‹ San Kɔ Guadwam",
    "checkout.refund_policy": "Sane a Wɔsan De Ma",
    "checkout.privacy_policy": "Kokoamsɛm Ho Mmara",
    "checkout.gift_card_placeholder": "Gift Card anaa Adeɛ a Agye Boɔ Kod",
    "checkout.apply": "Fa Di Dwuma",
    "checkout.remove": "Yi Fi Hɔ",
    "checkout.discount": "Deɛ Agye So",
    "checkout.shipping_label": "Nneɛma Kɔyɛ",
    "checkout.free": "Kwa",
    "checkout.total_label": "Ka a Wɔtua Nyinaa",
    "checkout.including": "Ka",
    "checkout.in_taxes": "toɔ ho",
    "checkout.checkout_with": "Fa Tua Ka Wɔ",
    "checkout.connecting": "Ɛreyɛ Sisi...",
    "checkout.processing_with": "Ɛreyɛ Akatua No Wɔ",
    "checkout.please_wait": "Yɛ Aboterɛ",
    "checkout.connecting_securely": "Ɛresisi banbɔ so kɔ akatua adwumakuo hɔ. Mmuta anaa nsan nyɛ krataa yi foforɔ.",

    // Shop / filters
    "shop.search_placeholder": "Hwehwɛ nneɛma...",
    "shop.filters": "Nhwehwɛmu",
    "shop.categories": "Nneɛma Mmoa",
    "shop.price_range": "Boɔ a Ɛda Mu",
    "shop.rating": "Nsɛnkyerɛnne",
    "shop.clear_filters": "Yi Nhwehwɛmu Nyinaa",
    "shop.sort_by": "Hyehyɛ Sɛnea",
    "shop.showing_results": "Ɛrekyerɛ Nsonsonoeɛ",
    "shop.grid_view": "Hwɛ Sɛ Kɛntɛnkɛntɛn",
    "shop.list_view": "Hwɛ Sɛ Listi",
    "shop.apply_filters": "Fa Nhwehwɛmu Di Dwuma",
    "shop.search_heading": "Hwehwɛ",
    "shop.by_rating": "Sɛnea Nsɛnkyerɛnne Teɛ",
    "shop.by_price": "Sɛnea Boɔ Teɛ",
    "shop.reset": "Sesa Foforɔ",
    "shop.price_prefix": "Boɔ:",
    "shop.and_up": "Ne Deɛ Ɛkorɔn",
    "shop.stars": "Nsoromma",

    // Product tabs
    "tabs.description": "Nkyerɛkyerɛmu",
    "tabs.specification": "Ne Su Nkyerɛkyerɛmu",
    "tabs.vendor": "Guadini",
    "tabs.reviews": "Nkaeɛ",
    "tabs.qa": "Nsɛmmisa ne Mmuaeɛ",
    "tabs.no_description": "Nkyerɛkyerɛmu biara nni adeɛ yi ho.",
  },
  fr: {
    // Navigation & Topbar
    "nav.home": "Accueil",
    "nav.shop": "Boutique",
    "nav.about": "À propos",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.dashboard": "Tableau de bord",
    "nav.admin_dashboard": "Tableau de bord Admin",
    "topbar.shopping_center": "Centre commercial pour toute commande de plus de GH₵100",
    "topbar.store_location": "Emplacement du magasin",
    "topbar.track_order": "Suivre votre commande",

    // Header & Search
    "search.all_categories": "Toutes les catégories",
    "search.placeholder": "Je recherche...",
    "search.mobile_placeholder": "Rechercher quelque chose...",
    "search.button": "Rechercher",
    "auth.login": "Connexion",
    "auth.register": "S'inscrire",
    "nav.navigation": "Navigation",

    // Hero Banner
    "hero.exclusive_deals": "Offres exclusives",
    "hero.up_to_50_off": "Jusqu'à 50% de réduction",
    "hero.shop_now": "Acheter maintenant",
    "hero.view_all_deals": "Voir toutes les offres",
    "hero.new_arrival": "Nouveauté",
    "hero.discover_now": "Découvrir maintenant →",
    "hero.limited_time": "Temps limité",
    "hero.save_big": "Économisez gros aujourd'hui →",

    // Cart & Wishlist
    "cart.title": "Panier",
    "cart.your_cart": "Votre panier",
    "cart.empty": "Votre panier est vide",
    "cart.empty_desc": "Ajoutez des articles à votre panier pour les voir ici.",
    "cart.checkout": "Passer à la caisse",
    "cart.subtotal": "Sous-total",
    "cart.total": "Total",
    "cart.add": "Ajouter au panier",
    "cart.in_cart": "Dans le panier",
    "cart.continue_shopping": "Continuer les achats",
    "wishlist.title": "Liste de souhaits",
    "wishlist.your_wishlist": "Votre liste de souhaits",
    "wishlist.empty": "Votre liste de souhaits est vide",
    "wishlist.empty_desc": "Enregistrez les articles que vous aimez pour plus tard.",
    "wishlist.view": "Voir",

    // Features
    "feature.free_delivery.title": "Livraison gratuite",
    "feature.free_delivery.desc": "Pour toute commande de plus de GH₵50",
    "feature.return.title": "Retour sous 90 jours",
    "feature.return.desc": "Si les articles ont un problème",
    "feature.payment.title": "Paiement sécurisé",
    "feature.payment.desc": "Paiement 100% sécurisé",
    "feature.support.title": "Support 24/7",
    "feature.support.desc": "Support dédié",

    // Sections & Products
    "section.category_month": "Meilleures catégories du mois",
    "section.deal_of_day": "Offre du jour",
    "section.recommended_for_you": "Recommandé pour vous",
    "section.end_in": "Se termine dans :",
    "section.view_all": "Voir tout",
    "section.groceries": "Épicerie fraîche et essentiels du quotidien",
    "section.electronics": "Électronique et accessoires numériques",
    "banner.summer_fashion": "Mode d'été",
    "banner.summer_discount": "Jusqu'à 40% de réduction sur une sélection",
    "status.fetching_styles": "Récupération des derniers styles...",
    "status.failed_load": "Échec du chargement des produits.",
    "status.no_products": "Aucun produit trouvé.",
    "product.each": "chacun",
    "product.out_of_stock": "Rupture de stock",
    "product.in_cart_badge": "Dans le panier ✓",
    "product.add_to_cart": "Ajouter au panier",
    "product.buy_now": "Acheter maintenant",
    "product.wishlisted": "Ajouté aux favoris",
    "product.add_to_wishlist": "Ajouter aux favoris",
    "product.sale": "Solde",

    // Footer
    "footer.quick_links": "Liens rapides",
    "footer.company": "Entreprise",
    "footer.business": "Affaires",
    "footer.newsletter": "Infolettre",
    "footer.subscribe": "S'abonner",
    "footer.email_placeholder": "Adresse e-mail",
    "footer.newsletter_desc": "Abonnez-vous pour recevoir des offres spéciales et des nouveautés",
    "footer.rights": "©2026 Martfury. Tous droits réservés.",
    "footer.safe_payment": "Nous utilisons un paiement sécurisé pour",
    "footer.policy": "Politique",
    "footer.terms": "Conditions générales",
    "footer.shipping": "Livraison",
    "footer.returns": "Retours",
    "footer.faqs": "FAQ",
    "footer.about": "À propos de nous",
    "footer.affiliate": "Affiliation",
    "footer.careers": "Carrières",
    "footer.contact": "Contact",
    "footer.our_press": "Notre presse",
    "footer.checkout": "Paiement",
    "footer.my_account": "Mon compte",
    "footer.shop": "Boutique",

    // Account & Mobile
    "account.title": "Compte",
    "language.title": "Langue",
    "language.en": "Anglais",
    "language.tw": "Twi",

    // Checkout
    "checkout.contact_information": "Coordonnées",
    "checkout.already_have_account": "Vous avez déjà un compte ?",
    "checkout.log_in": "Se connecter",
    "checkout.email_placeholder": "E-mail",
    "checkout.email_offers": "M'envoyer des actualités et des offres par e-mail",
    "checkout.shipping_address": "Adresse de livraison",
    "checkout.first_name": "Prénom",
    "checkout.last_name": "Nom",
    "checkout.company_optional": "Entreprise (facultatif)",
    "checkout.address_placeholder": "Adresse",
    "checkout.suburb_placeholder": "Quartier",
    "checkout.country_region": "Pays/région",
    "checkout.state_territory": "État/région",
    "checkout.postcode_placeholder": "Code postal",
    "checkout.phone_placeholder": "Téléphone",
    "checkout.return_to_shop": "‹ Retour à la boutique",
    "checkout.refund_policy": "Politique de remboursement",
    "checkout.privacy_policy": "Politique de confidentialité",
    "checkout.gift_card_placeholder": "Carte cadeau ou code de réduction",
    "checkout.apply": "Appliquer",
    "checkout.remove": "Retirer",
    "checkout.discount": "Réduction",
    "checkout.shipping_label": "Livraison",
    "checkout.free": "Gratuit",
    "checkout.total_label": "Total",
    "checkout.including": "Incluant",
    "checkout.in_taxes": "de taxes",
    "checkout.checkout_with": "Payer avec",
    "checkout.connecting": "Connexion...",
    "checkout.processing_with": "Traitement du paiement avec",
    "checkout.please_wait": "Veuillez patienter",
    "checkout.connecting_securely": "Connexion sécurisée au fournisseur de paiement. Ne fermez pas et n'actualisez pas cette page.",

    // Shop / filters
    "shop.search_placeholder": "Rechercher des produits...",
    "shop.filters": "Filtres",
    "shop.categories": "Catégories",
    "shop.price_range": "Fourchette de prix",
    "shop.rating": "Évaluation",
    "shop.clear_filters": "Effacer les filtres",
    "shop.sort_by": "Trier par",
    "shop.showing_results": "Résultats affichés",
    "shop.grid_view": "Vue en grille",
    "shop.list_view": "Vue en liste",
    "shop.apply_filters": "Appliquer les filtres",
    "shop.search_heading": "Recherche",
    "shop.by_rating": "Par évaluation",
    "shop.by_price": "Par prix",
    "shop.reset": "Réinitialiser",
    "shop.price_prefix": "Prix :",
    "shop.and_up": "et plus",
    "shop.stars": "étoiles",

    // Product tabs
    "tabs.description": "Description",
    "tabs.specification": "Caractéristiques",
    "tabs.vendor": "Vendeur",
    "tabs.reviews": "Avis",
    "tabs.qa": "Questions & Réponses",
    "tabs.no_description": "Aucune description disponible pour ce produit.",
  },
  // ⚠️ Ewe (Eʋegbe) — machine-drafted for coverage, not verified by a
  // native speaker. Flagged per project decision: ship now, have a fluent
  // reviewer correct wording before this goes in front of real users.
  ewe: {
    "nav.home": "Aƒeme",
    "nav.shop": "Asi",
    "nav.about": "Ŋuɖoɖo mía ŋu",
    "nav.blog": "Blog",
    "nav.contact": "Kadodo",
    "nav.dashboard": "Dziɖuɖudzesi",
    "nav.admin_dashboard": "Amegã ƒe Dziɖuɖudzesi",
    "topbar.shopping_center": "Asiƒe na nudzadza siwo wu GH₵100",
    "topbar.store_location": "Afisi asitsaƒea le",
    "topbar.track_order": "Kpɔ wò nudzadza ɖa",

    "search.all_categories": "Nusiwo katã",
    "search.placeholder": "Mele nu dim...",
    "search.mobile_placeholder": "Di nane...",
    "search.button": "Di",
    "auth.login": "Ge ɖe eme",
    "auth.register": "Ŋlɔ wò ŋkɔ",
    "nav.navigation": "Mɔfiafia",

    "hero.exclusive_deals": "Asidzadada tɔxɛwo",
    "hero.up_to_50_off": "Asiɖeɖe va se ɖe 50%",
    "hero.shop_now": "Ƒle fifia",
    "hero.view_all_deals": "Kpɔ asidzadadawo katã",
    "hero.new_arrival": "Nu Yeye",
    "hero.discover_now": "Di nu fifia →",
    "hero.limited_time": "Ɣeyiɣi kpui",
    "hero.save_big": "Dzra ga geɖe egbe →",

    "cart.title": "Kusi",
    "cart.your_cart": "Wò Kusi",
    "cart.empty": "Wò kusi le ƒuƒlu",
    "cart.empty_desc": "Tsɔ nuwo de wò kusi me be nàkpɔ wo le afii.",
    "cart.checkout": "Xe fe",
    "cart.subtotal": "Ga siwo katã",
    "cart.total": "Ga bliboa",
    "cart.add": "Tsɔ de kusi me",
    "cart.in_cart": "Ele kusi me",
    "cart.continue_shopping": "Yi asitsatsa dzi",
    "wishlist.title": "Nu didiwo",
    "wishlist.your_wishlist": "Wò Nu Didiwo",
    "wishlist.empty": "Nu aɖeke mele wò didilistoa me o",
    "wishlist.empty_desc": "Dzra nusiwo nèlɔ̃ ɖo na emegbe.",
    "wishlist.view": "Kpɔ",

    "feature.free_delivery.title": "Nutsɔtsɔ Femaxee",
    "feature.free_delivery.desc": "Na nudzadza siwo wu GH₵50",
    "feature.return.title": "Ŋkeke 90 Trɔtrɔ",
    "feature.return.desc": "Ne kuxi le nua ŋu",
    "feature.payment.title": "Fexexe si dedie",
    "feature.payment.desc": "Fexexe si dedie 100%",
    "feature.support.title": "Kpekpeɖeŋu Ɣesiaɣi (24/7)",
    "feature.support.desc": "Kpekpeɖeŋu tɔxɛ",

    "section.category_month": "Nudzadza siwo xɔ asi le dzinu sia me",
    "section.deal_of_day": "Asidzadada le egbe",
    "section.recommended_for_you": "Nusi wode dzesi na wò",
    "section.end_in": "Ewu enu le:",
    "section.view_all": "Kpɔ Katã",
    "section.groceries": "Nuɖuɖu Yeye kple Nu Hiãwo",
    "section.electronics": "Elektroniku kple Kpeɖodzinuwo",
    "banner.summer_fashion": "Dzoxɔxɔŋɔli Awuwo",
    "banner.summer_discount": "Asiɖeɖe va se ɖe 40%",
    "status.fetching_styles": "Ele nu yeyewo dim...",
    "status.failed_load": "Nudzadzawo mete ŋu va o.",
    "status.no_products": "Womekpɔ nudzadza aɖeke o.",
    "product.each": "ɖeka ɖeka",
    "product.out_of_stock": "Vɔ le fiase",
    "product.in_cart_badge": "Ele kusi me ✓",
    "product.add_to_cart": "Tsɔ de kusi me",
    "product.buy_now": "Ƒle fifia",
    "product.wishlisted": "Wode ɖe didilist me",
    "product.add_to_wishlist": "Tsɔ de didilist me",
    "product.sale": "Asiɖeɖe",

    "footer.quick_links": "Kadodo kpuiwo",
    "footer.company": "Dɔwɔƒe",
    "footer.business": "Asitsatsa",
    "footer.newsletter": "Nyadzɔdzɔ",
    "footer.subscribe": "Ŋlɔ wò ŋkɔ",
    "footer.email_placeholder": "Wò Email",
    "footer.newsletter_desc": "Ŋlɔ wò ŋkɔ be nàxɔ asiɖeɖe tɔxɛwo kple nyatakakawo",
    "footer.rights": "©2026 Martfury. Gome katã le eŋu.",
    "footer.safe_payment": "Míezãa Fexexe Dedie Na",
    "footer.policy": "Sedede",
    "footer.terms": "Se kple Ɖoɖowo",
    "footer.shipping": "Nutsɔtsɔ",
    "footer.returns": "Nutrɔtrɔ",
    "footer.faqs": "Biabia Gbɔgblɔwo",
    "footer.about": "Ŋuɖoɖo Mía Ŋu",
    "footer.affiliate": "Habɔbɔ",
    "footer.careers": "Dɔwɔƒewo",
    "footer.contact": "Kadodo",
    "footer.our_press": "Míaƒe Nyadzɔdzɔ",
    "footer.checkout": "Fexexe",
    "footer.my_account": "Nye Akɔntabubu",
    "footer.shop": "Asi",

    "account.title": "Akɔntabubu",
    "language.title": "Gbe",
    "language.en": "English",
    "language.tw": "Twi",

    // Checkout
    "checkout.contact_information": "Wò Ŋkɔdzɔdzɔ",
    "checkout.already_have_account": "Akɔntabubu le asiwò xoxoxo?",
    "checkout.log_in": "Ge ɖe eme",
    "checkout.email_placeholder": "Email",
    "checkout.email_offers": "Ɖo nyadzɔdzɔ kple asiɖeɖe ɖem to email dzi",
    "checkout.shipping_address": "Afisi Woatsɔ Nuwo Ayi",
    "checkout.first_name": "Ŋkɔ Gbãtɔ",
    "checkout.last_name": "Ƒomeŋkɔ",
    "checkout.company_optional": "Dɔwɔƒe (Mehiã o)",
    "checkout.address_placeholder": "Afi",
    "checkout.suburb_placeholder": "Kɔƒenu",
    "checkout.country_region": "Dukɔ/Nutome",
    "checkout.state_territory": "Nutome",
    "checkout.postcode_placeholder": "Post Nɔmba",
    "checkout.phone_placeholder": "Kaƒomɔ Nɔmba",
    "checkout.return_to_shop": "‹ Trɔ Yi Asi",
    "checkout.refund_policy": "Nutrɔtrɔ Se",
    "checkout.privacy_policy": "Ŋutasesẽ Ƒe Se",
    "checkout.gift_card_placeholder": "Gift Card alo Asiɖeɖe Kod",
    "checkout.apply": "Zã",
    "checkout.remove": "Ɖe Ɖa",
    "checkout.discount": "Asiɖeɖe",
    "checkout.shipping_label": "Nutsɔtsɔ",
    "checkout.free": "Femaxee",
    "checkout.total_label": "Ga Bliboa",
    "checkout.including": "Kpe ɖe",
    "checkout.in_taxes": "adzɔ ŋu",
    "checkout.checkout_with": "Xe Fe Kple",
    "checkout.connecting": "Ele ɖoɖom...",
    "checkout.processing_with": "Ele fexexe wɔm kple",
    "checkout.please_wait": "Taɖodzinu",
    "checkout.connecting_securely": "Ele ɖoɖom dedie kple fexexe subɔla. Mègatu alo nàgade axa sia me o.",

    // Shop / filters
    "shop.search_placeholder": "Di nudzadzawo...",
    "shop.filters": "Tiatiã",
    "shop.categories": "Nusiwo Katã",
    "shop.price_range": "Asi Ƒe Lolome",
    "shop.rating": "Akɔntabubu",
    "shop.clear_filters": "Ɖe Tiatiãwo Katã Ɖa",
    "shop.sort_by": "Ɖo Ɖe",
    "shop.showing_results": "Ele Nutsudɔwo Fiam",
    "shop.grid_view": "Kpɔ Abe Kɛnɛtɛ Ene",
    "shop.list_view": "Kpɔ Abe List Ene",
    "shop.apply_filters": "Zã Tiatiãwo",
    "shop.search_heading": "Didi",
    "shop.by_rating": "Le Akɔntabubu Nu",
    "shop.by_price": "Le Asi Nu",
    "shop.reset": "Trɔ Yeye",
    "shop.price_prefix": "Asi:",
    "shop.and_up": "kple wu",
    "shop.stars": "Ɣletiviwo",

    // Product tabs
    "tabs.description": "Numeɖeɖe",
    "tabs.specification": "Nudzɔdzɔwo",
    "tabs.vendor": "Asitsala",
    "tabs.reviews": "Nyaŋuɖoɖowo",
    "tabs.qa": "Biabia kple Ŋuɖoɖo",
    "tabs.no_description": "Numeɖeɖe aɖeke mele nu sia ŋu o.",
  },
  // ⚠️ Ga — also machine-drafted, same caveat as Ewe above: needs a
  // native-speaker pass before production use.
  ga: {
    "nav.home": "Shĩa",
    "nav.shop": "Jara",
    "nav.about": "Wɔ He Sane",
    "nav.blog": "Blog",
    "nav.contact": "Kɛ Wɔ Kpã",
    "nav.dashboard": "Nɔkwɛlɔ Akpo",
    "nav.admin_dashboard": "Onukpa Akpo",
    "topbar.shopping_center": "Jaraheiaŋ kɛha nihei fɛɛ ni fá GH₵100",
    "topbar.store_location": "He ni Jarayeli lɛ Yɔɔ",
    "topbar.track_order": "Kwɛmɔ Onitɔ̃ɔ",

    "search.all_categories": "Nihei Fɛɛ",
    "search.placeholder": "Mimiitao nɔ ko...",
    "search.mobile_placeholder": "Taomɔ nɔ ko...",
    "search.button": "Taomɔ",
    "auth.login": "Bɔlɔ",
    "auth.register": "Ŋmalɔ Ogbɛi",
    "nav.navigation": "Gbɛtsɔɔmɔ",

    "hero.exclusive_deals": "Nihei ni Yɔɔ Krɔŋŋ",
    "hero.up_to_50_off": "Shɔ kɛyaa 50%",
    "hero.shop_now": "Jara Amrɔ Nɔŋŋ",
    "hero.view_all_deals": "Kwɛ Nihei Fɛɛ",
    "hero.new_arrival": "Nihei Hei",
    "hero.discover_now": "Na Nɔ Amrɔ Nɔŋŋ →",
    "hero.limited_time": "Bɛ Kuku",
    "hero.save_big": "Bɔ Shika Babaoo Ŋmɛnɛ →",

    "cart.title": "Kɛntɛn",
    "cart.your_cart": "Okɛntɛn",
    "cart.empty": "Okɛntɛn lɛ Yɛ Amamu",
    "cart.empty_desc": "Kɛ nihei wo okɛntɛn lɛ mli koni ona amɛ biɛ.",
    "cart.checkout": "Wo Shika",
    "cart.subtotal": "Fɛɛ Naa",
    "cart.total": "Fɛɛ Fɛɛ",
    "cart.add": "Kɛwo Kɛntɛn Lɛ Mli",
    "cart.in_cart": "Eyɛ Kɛntɛn Lɛ Mli",
    "cart.continue_shopping": "Ya Nɔ Kɛ Jaraa",
    "wishlist.title": "Nihei ni Osumɔɔ",
    "wishlist.your_wishlist": "Onihei ni Osumɔɔ",
    "wishlist.empty": "Nɔ ko Bɛ Onihei-ni-osumɔɔ Lɛ Mli",
    "wishlist.empty_desc": "Yeli nihei ni osumɔɔ ake sɛɛ mli.",
    "wishlist.view": "Kwɛ",

    "feature.free_delivery.title": "Yiwoo ni Yeee Shika",
    "feature.free_delivery.desc": "Kɛha nihei fɛɛ ni fá GH₵50",
    "feature.return.title": "Gbii 90 Kutsɔ",
    "feature.return.desc": "Kɛji nɔ lɛ eyɛ tɔmɔ",
    "feature.payment.title": "Shikawoo ni Yɔɔ Shweshweeshwe",
    "feature.payment.desc": "Shikawoo ni Yɔɔ Shweshweeshwe 100%",
    "feature.support.title": "Yelikɛbuamɔ Bei Fɛɛ Bei (24/7)",
    "feature.support.desc": "Yelikɛbuamɔ ni Sa",

    "section.category_month": "Nihei ni Yɔɔ Krɔŋŋ Nyɔɔŋ Nɛɛ Mli",
    "section.deal_of_day": "Gbi Nɛɛ Niheiyeli",
    "section.recommended_for_you": "Nɔ ni Wɔjɔɔ Kɛha Bo",
    "section.end_in": "Enaa Yaa Naa Yɛ:",
    "section.view_all": "Kwɛ Fɛɛ",
    "section.groceries": "Nyɔmɔ Hee kɛ Gbii Fɛɛ Nihei",
    "section.electronics": "Elektroniki kɛ Ekɛkpee Nihei",
    "banner.summer_fashion": "Kɔɔyɔɔ Atadei",
    "banner.summer_discount": "Shɔ kɛyaa 40%",
    "status.fetching_styles": "Wɔmiiná nihei hee lɛ...",
    "status.failed_load": "Nihei lɛ baaa jogbaŋŋ.",
    "status.no_products": "Ana nihei ko.",
    "product.each": "eko eko",
    "product.out_of_stock": "Ebɛ Jarayeli Lɛ Mli",
    "product.in_cart_badge": "Eyɛ Kɛntɛn Lɛ Mli ✓",
    "product.add_to_cart": "Kɛwo Kɛntɛn Lɛ Mli",
    "product.buy_now": "Jara Amrɔ Nɔŋŋ",
    "product.wishlisted": "Ekɛwo Nihei-ni-osumɔɔ Lɛ Mli",
    "product.add_to_wishlist": "Kɛwo Nihei-ni-osumɔɔ Lɛ Mli",
    "product.sale": "Shɔɔ",

    "footer.quick_links": "Gbɛtsɔɔmɔi ni Ha Oyaa Oyera",
    "footer.company": "Gbɛtsɔɔmɔ",
    "footer.business": "Nikasemɔ",
    "footer.newsletter": "Wolo Bibioo",
    "footer.subscribe": "Ŋmalɔ Ogbɛi",
    "footer.email_placeholder": "Oimeli",
    "footer.newsletter_desc": "Ŋmalɔ Ogbɛi Koni Ona Nihei Krɔŋŋ kɛ Sane Hei",
    "footer.rights": "©2026 Martfury. Toi Fɛɛ Yɛ He.",
    "footer.safe_payment": "Wɔkɛ Shikawoo ni Yɔɔ Shweshweeshwe Tsuɔ Nii Kɛha",
    "footer.policy": "Mla",
    "footer.terms": "Mlai kɛ Gbɛjianɔtoi",
    "footer.shipping": "Yiwoo",
    "footer.returns": "Kutsɔmɔ",
    "footer.faqs": "Sanebimɔi ni Baa Pɛpɛɛpɛ",
    "footer.about": "Wɔ He Sane",
    "footer.affiliate": "Kpaŋmɔ",
    "footer.careers": "Nitsumɔhei",
    "footer.contact": "Kɛ Wɔ Kpã",
    "footer.our_press": "Wɔ Sanegbaa",
    "footer.checkout": "Shikawoo",
    "footer.my_account": "Mi Akɔnta",
    "footer.shop": "Jara",

    "account.title": "Akɔnta",
    "language.title": "Wiemɔ",
    "language.en": "English",
    "language.tw": "Twi",

    // Checkout
    "checkout.contact_information": "Okɛ Bo Kpãa He Sane",
    "checkout.already_have_account": "Oyɛ Akɔnta Momo Lɛ?",
    "checkout.log_in": "Bɔlɔ",
    "checkout.email_placeholder": "Imeli",
    "checkout.email_offers": "Kɛ sane hei kɛ nihei ni yɔɔ krɔŋŋ ba mi imeli",
    "checkout.shipping_address": "He ni Woyiwoo Nihei",
    "checkout.first_name": "Klɛŋklɛŋ Gbɛi",
    "checkout.last_name": "Weku Gbɛi",
    "checkout.company_optional": "Gbɛtsɔɔmɔ (Ehiaaa)",
    "checkout.address_placeholder": "He",
    "checkout.suburb_placeholder": "Akutso",
    "checkout.country_region": "Maŋ/Kpokpaa",
    "checkout.state_territory": "Kpokpaa",
    "checkout.postcode_placeholder": "Post Nɔmba",
    "checkout.phone_placeholder": "Tɛlɛfoŋ Nɔmba",
    "checkout.return_to_shop": "‹ Ku Sɛɛ Kɛyaa Jara",
    "checkout.refund_policy": "Kutsɔmɔ Mla",
    "checkout.privacy_policy": "Teemɔ Mla",
    "checkout.gift_card_placeholder": "Gift Card loo Shɔ Kod",
    "checkout.apply": "Kɛtsu Nii",
    "checkout.remove": "Jie Kɛjɛ Mli",
    "checkout.discount": "Shɔɔ",
    "checkout.shipping_label": "Yiwoo",
    "checkout.free": "Yeee Shika",
    "checkout.total_label": "Fɛɛ Fɛɛ",
    "checkout.including": "Kɛ Fata He",
    "checkout.in_taxes": "toohei",
    "checkout.checkout_with": "Wo Shika Kɛ",
    "checkout.connecting": "Ekɛkpe...",
    "checkout.processing_with": "Etsuɔ Shikawoo Lɛ He Nii Kɛ",
    "checkout.please_wait": "Tamɔ Bo",
    "checkout.connecting_securely": "Ekɛkpe shwɛshwɛɛshwɛ kɛ shikawoo tsulɔ lɛ. Kaŋmɛɛɛ loo kaŋkpɛlɛ shashimɔ nɛɛ mli.",

    // Shop / filters
    "shop.search_placeholder": "Taomɔ nihei...",
    "shop.filters": "Hesabu",
    "shop.categories": "Nihei Mli Kui",
    "shop.price_range": "Jara Mli",
    "shop.rating": "Sanebuu",
    "shop.clear_filters": "Jie Hesabui Lɛ Fɛɛ Kɛjɛ Mli",
    "shop.sort_by": "To Gbɛjianɔ Kɛtsɔ",
    "shop.showing_results": "Ekɛtsɔɔ Nɔ Ni Ana",
    "shop.grid_view": "Kwɛ Kɛtsɔ Kɛntɛn Nɔ",
    "shop.list_view": "Kwɛ Kɛtsɔ List Nɔ",
    "shop.apply_filters": "Kɛtsu Hesabui Lɛ He Nii",
    "shop.search_heading": "Taomɔ",
    "shop.by_rating": "Kɛtsɔ Sanebuu Nɔ",
    "shop.by_price": "Kɛtsɔ Jara Nɔ",
    "shop.reset": "To Ekoŋŋ",
    "shop.price_prefix": "Jara:",
    "shop.and_up": "kɛ nɔ ni fa",
    "shop.stars": "Ŋulami",

    // Product tabs
    "tabs.description": "Shishitsɔɔmɔ",
    "tabs.specification": "He Sane Kpɛlɛmɔi",
    "tabs.vendor": "Jaralɔ",
    "tabs.reviews": "Sanebuui",
    "tabs.qa": "Sanebimɔi kɛ Hetoi",
    "tabs.no_description": "Shishitsɔɔmɔ ko bɛ nɔ nɛɛ he.",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey | string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LOCAL_STORAGE_KEY = "martfury_lang";

const ALL_LANGUAGES: Language[] = ["en", "tw", "fr", "ewe", "ga"];

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(LOCAL_STORAGE_KEY);
      // Was only ever checking for "en"/"tw" — added fr/ewe/ga later and
      // never updated this, so a stored preference for any of the three
      // newer languages was silently ignored on every remount (any dev
      // Fast Refresh included), snapping the whole app back to English.
      if (stored && (ALL_LANGUAGES as string[]).includes(stored)) {
        setLanguageState(stored as Language);
      }
    } catch {
      // localStorage read failed or not available
    } finally {
      setIsInitialized(true);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(LOCAL_STORAGE_KEY, lang);
      document.documentElement.lang = lang;
    } catch {
      // localStorage write failed
    }
  };

  const toggleLanguage = () => {
    setLanguage(language === "en" ? "tw" : "en");
  };

  const t = (key: TranslationKey | string, fallback?: string): string => {
    const langDict = translations[language];
    if (key in langDict) {
      return langDict[key as TranslationKey];
    }
    return fallback ?? key;
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        toggleLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
